CREATE TABLE IF NOT EXISTS rating_MPA (
    id_MPA INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_MPA VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS genre (
    id_genre INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS user (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    login VARCHAR(100) NOT NULL,
    name VARCHAR(100),
    birthday DATE
);


CREATE TABLE IF NOT EXISTS film (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(100),
    release_date DATE,
    duration INTEGER,
    genre_id INTEGER,
    rating_MPA_id INTEGER,
    CONSTRAINT fk_film_rating FOREIGN KEY (rating_MPA_id) REFERENCES rating_MPA (id_MPA)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id INTEGER REFERENCES film (id),
    genre_id INTEGER REFERENCES genre (id_genre),
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS friends (
    user_id INTEGER REFERENCES user (id),
    friend_id INTEGER REFERENCES user (id),
    status BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS storage_user_film_like (
    user_id INTEGER REFERENCES user (id),
    film_id INTEGER REFERENCES film (id),
    PRIMARY KEY (user_id, film_id)
);
