CREATE TABLE IF NOT EXISTS mpa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_MPA VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS genre (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    login VARCHAR(100) NOT NULL,
    username VARCHAR(100),
    birthday DATE
);


CREATE TABLE IF NOT EXISTS film (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(100),
    release_date DATE,
    duration INTEGER,
    genre_id INTEGER,
    rating_MPA_id INTEGER,
    CONSTRAINT fk_film_rating FOREIGN KEY (rating_MPA_id) REFERENCES mpa (id)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id BIGINT REFERENCES film (id),
    genre_id BIGINT REFERENCES genre (id),
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS friends (
    user_id BIGINT REFERENCES users (id),
    friend_id BIGINT REFERENCES users (id),
    status BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS storage_user_film_like (
    user_id BIGINT REFERENCES users (id),
    film_id BIGINT REFERENCES film (id),
    PRIMARY KEY (user_id, film_id)
);